title: PGCoE Considerations for Public Release of Pathogen Data
description: A Pathogen Genomics Centers of Excellence (PGCoE) guide to considerations for public release of pathogen data by public health agencies.
theme: just-the-docs

url: https://garfinjm.github.io/pgcoe-data-release/

logo: "/docs/media/pgcoe-network-graphic-element.png"
favicon_ico: "/docs/media/pgcoe-network-graphic-element.png"

aux_links:
  PGCoE Main Site: https://pgcoe.github.io/

callouts:
  mitigation:
    title: Mitigation Strategy
    color: blue
  cost:
    title: Cost
    color: green
  prevalence:
    title: Prevalence of Strategy
    color: purple
