title: PGCoE Considerations for Public Release of Pathogen Data
description: A Pathogen Genomics Centers of Excellence (PGCoE) guide to considerations for public release of pathogen data by public health agencies.
theme: just-the-docs

url: https://garfinjm.github.io/pgcoe-data-release/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


callouts:
  mitigation:
    title: Mitigation Strategy
    color: blue
  cost:
    title: Cost
    color: green
  prevalence:
    title: Prevalence of Strategy
    color: purple
